# Generated by Django 2.0.6 on 2018-06-19 11:29

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[blog.validators.validate_users_mail]),
        ),
    ]
